### ISSUE TITLE
[IMPROVEMENT] Even More Food Items

### ISSUE THREAD

**Issue by beanbeanjuice** [beanbeanjuice/cafeBot#516]
**__Describe the Improvement__**
Add even more items, and fix some of the old ones.

Old Ones;
- [x] Among Us Chicken Nugget
 - Section: Meme Food
 - Descriptions: A **sus**piciously shaped chicken nugget, originally purchased for 99,997 bC. ~~Has probably been sitting on a shelf somewhere waiting to be purchased for a while. I would not eat this...~~
 - Price 9.99 bC

New Ones:
- [x] Link's Special ~~Dubious Food~~
 - Section: Meme Food
 - Description: A dish made up of thrown-together leftovers and scraps. ~~It's actually too gross to even look at. Eating it won't hurt you though... probably.~~
 - Price: 1.0 bC
 - Image: 
![image](https://user-images.githubusercontent.com/64740551/182534014-5030b8a8-7c7b-4d13-803a-492f60a8dbff.png)

- [x] Super Mario Shrooms
 - Section: Secret Menu
 - Description: Just a bowl of mushrooms and veggies. ~~May cause you to grow or possibly turn you into a cat.~~
 - Price: 10.00 bC
 - Image: 
![image](https://user-images.githubusercontent.com/64740551/182534294-f0235e78-d45f-4429-bed7-71f3776d2ffe.png)

- [x] Yoda Soda
 - Section: Meme Food
 - Description: An ice cream float made by a school cafeteria. Can only be served on May 4th... but it's gotta be May 4th somewhere, right?
 - Price: 2.0 bC
 - Image: 
![image](https://user-images.githubusercontent.com/64740551/182534482-0958d7f4-fdbf-4375-82c0-746a5992ebd6.png)

# Checklist:

- [x] I have checked for similar issues.
- [x] This is an improvement request, not a feature request, bug report, or security vulnerability report.

**Comment by yaioqin** [comment]
Is this work still ongoing?I am a beginner and would like to give it a try.
