### ISSUE TITLE
[BUG] Multiple words in the "word" parameter of "/serve" causes the bot to think indefinitely 

### ISSUE THREAD

**Issue by Firepup6500** [beanbeanjuice/cafeBot#517]
**__Describe the Bug__**
If you input more than one word into the "word" parameter of "/serve", the bot just thinks indefinitely

**__Steps To Reproduce__**
1. Run /serve word:demo test user:test
2. See error

**__Expected Behavior__**
The bot to either:
1. Throw an error stating that there can only be one word
2. Just use all the words as the thing to serve (ex:chocolate cake)

**__Screenshots/Videos__**
![Screenshot 1](https://user-images.githubusercontent.com/70233190/183431808-e8c0d51e-0844-4069-9f73-8e9f4ed5dcce.jpg)
![Screenshot 2](https://user-images.githubusercontent.com/70233190/183431813-880a7dac-eeeb-4d2a-984c-cfd850cc08b3.jpg)

**__Additional Context__**

# Checklist:

- [x] I have checked for similar issues.
- [x] This is a bug report, not a feature request, improvement request, or security vulnerability report.

**Comment by beanbeanjuice** [comment]
Thank you for letting me know! I'll get this fixed ASAP.

**Comment by Firepup6500** [comment]
Yep! Happy to help!
