### ISSUE TITLE
[BUG] Quesadilla Not a Word

### ISSUE THREAD

**Issue by JatziriNANI** [beanbeanjuice/cafeBot#552]
**__Describe the Bug__**
I used the /serve command and typed "quesadilla" for what i wanted to serve and it said that it wasn't a word.

**__Steps To Reproduce__**
1. Go to any channel
2. Type the command: /serve word:quesadilla 
3. Press enter

**__Expected Behavior__**
To serve the word i told it to.

**__Screenshots/Videos__**
![Screenshot_20230304-110812-482](https://user-images.githubusercontent.com/126976741/222919333-fc7caa9b-29e4-4d11-b889-6c82d0e258be.png)
![Screenshot_20230304-110823-466](https://user-images.githubusercontent.com/126976741/222919336-3c6ec8b8-4c2f-4513-97da-5fcba02847b9.png)

# Checklist:

[ ] I have checked for similar issues.
[✓]This is a bug report, not a feature request, improvement request, or security vulnerability report.

**Comment by beanbeanjuice** [comment]
Will add this in the next update!

**Comment by beanbeanjuice** [comment]
Closing. Word will be added by the next update.
